/**
 * Fess - User API
 * This is a Fess Server based on the OpenAPI 3.0 specification.  
 *
 * The version of the OpenAPI document: 14.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Error from './model/Error';
import FindSuggestWords200Response from './model/FindSuggestWords200Response';
import FindSuggestWords200ResponseDataInner from './model/FindSuggestWords200ResponseDataInner';
import ListFavorites200Response from './model/ListFavorites200Response';
import ListFavorites200ResponseDataInner from './model/ListFavorites200ResponseDataInner';
import ListLPopularWords200Response from './model/ListLPopularWords200Response';
import ListLabels200Response from './model/ListLabels200Response';
import ListLabels200ResponseDataInner from './model/ListLabels200ResponseDataInner';
import Ping200Response from './model/Ping200Response';
import Ping200ResponseData from './model/Ping200ResponseData';
import SearchDocuments200Response from './model/SearchDocuments200Response';
import SearchDocuments200ResponseDataInner from './model/SearchDocuments200ResponseDataInner';
import SetFavorite201Response from './model/SetFavorite201Response';
import FavoriteApi from './api/FavoriteApi';
import MonitorApi from './api/MonitorApi';
import PopularwordApi from './api/PopularwordApi';
import SearchApi from './api/SearchApi';
import SuggestApi from './api/SuggestApi';


/**
* This is a Fess Server based on the OpenAPI 3.0 specification.  .<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var FessUserApi = require('index'); // See note below*.
* var xxxSvc = new FessUserApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new FessUserApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new FessUserApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new FessUserApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 14.8.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The FindSuggestWords200Response model constructor.
     * @property {module:model/FindSuggestWords200Response}
     */
    FindSuggestWords200Response,

    /**
     * The FindSuggestWords200ResponseDataInner model constructor.
     * @property {module:model/FindSuggestWords200ResponseDataInner}
     */
    FindSuggestWords200ResponseDataInner,

    /**
     * The ListFavorites200Response model constructor.
     * @property {module:model/ListFavorites200Response}
     */
    ListFavorites200Response,

    /**
     * The ListFavorites200ResponseDataInner model constructor.
     * @property {module:model/ListFavorites200ResponseDataInner}
     */
    ListFavorites200ResponseDataInner,

    /**
     * The ListLPopularWords200Response model constructor.
     * @property {module:model/ListLPopularWords200Response}
     */
    ListLPopularWords200Response,

    /**
     * The ListLabels200Response model constructor.
     * @property {module:model/ListLabels200Response}
     */
    ListLabels200Response,

    /**
     * The ListLabels200ResponseDataInner model constructor.
     * @property {module:model/ListLabels200ResponseDataInner}
     */
    ListLabels200ResponseDataInner,

    /**
     * The Ping200Response model constructor.
     * @property {module:model/Ping200Response}
     */
    Ping200Response,

    /**
     * The Ping200ResponseData model constructor.
     * @property {module:model/Ping200ResponseData}
     */
    Ping200ResponseData,

    /**
     * The SearchDocuments200Response model constructor.
     * @property {module:model/SearchDocuments200Response}
     */
    SearchDocuments200Response,

    /**
     * The SearchDocuments200ResponseDataInner model constructor.
     * @property {module:model/SearchDocuments200ResponseDataInner}
     */
    SearchDocuments200ResponseDataInner,

    /**
     * The SetFavorite201Response model constructor.
     * @property {module:model/SetFavorite201Response}
     */
    SetFavorite201Response,

    /**
    * The FavoriteApi service constructor.
    * @property {module:api/FavoriteApi}
    */
    FavoriteApi,

    /**
    * The MonitorApi service constructor.
    * @property {module:api/MonitorApi}
    */
    MonitorApi,

    /**
    * The PopularwordApi service constructor.
    * @property {module:api/PopularwordApi}
    */
    PopularwordApi,

    /**
    * The SearchApi service constructor.
    * @property {module:api/SearchApi}
    */
    SearchApi,

    /**
    * The SuggestApi service constructor.
    * @property {module:api/SuggestApi}
    */
    SuggestApi
};
