/**
 * Fess - User API
 * This is a Fess Server based on the OpenAPI 3.0 specification.  
 *
 * The version of the OpenAPI document: 14.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FindSuggestWords200ResponseDataInner from './FindSuggestWords200ResponseDataInner';

/**
 * The FindSuggestWords200Response model module.
 * @module model/FindSuggestWords200Response
 * @version 14.8.0
 */
class FindSuggestWords200Response {
    /**
     * Constructs a new <code>FindSuggestWords200Response</code>.
     * @alias module:model/FindSuggestWords200Response
     */
    constructor() { 
        
        FindSuggestWords200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FindSuggestWords200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FindSuggestWords200Response} obj Optional instance to populate.
     * @return {module:model/FindSuggestWords200Response} The populated <code>FindSuggestWords200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FindSuggestWords200Response();

            if (data.hasOwnProperty('query_time')) {
                obj['query_time'] = ApiClient.convertToType(data['query_time'], 'Number');
            }
            if (data.hasOwnProperty('record_count')) {
                obj['record_count'] = ApiClient.convertToType(data['record_count'], 'Number');
            }
            if (data.hasOwnProperty('page_size')) {
                obj['page_size'] = ApiClient.convertToType(data['page_size'], 'Number');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [FindSuggestWords200ResponseDataInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FindSuggestWords200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FindSuggestWords200Response</code>.
     */
    static validateJSON(data) {
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                FindSuggestWords200ResponseDataInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Number} query_time
 */
FindSuggestWords200Response.prototype['query_time'] = undefined;

/**
 * @member {Number} record_count
 */
FindSuggestWords200Response.prototype['record_count'] = undefined;

/**
 * @member {Number} page_size
 */
FindSuggestWords200Response.prototype['page_size'] = undefined;

/**
 * @member {Array.<module:model/FindSuggestWords200ResponseDataInner>} data
 */
FindSuggestWords200Response.prototype['data'] = undefined;






export default FindSuggestWords200Response;

