/**
 * Fess - User API
 * This is a Fess Server based on the OpenAPI 3.0 specification.  
 *
 * The version of the OpenAPI document: 14.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SearchDocuments200ResponseDataInner from './SearchDocuments200ResponseDataInner';

/**
 * The SearchDocuments200Response model module.
 * @module model/SearchDocuments200Response
 * @version 14.8.0
 */
class SearchDocuments200Response {
    /**
     * Constructs a new <code>SearchDocuments200Response</code>.
     * @alias module:model/SearchDocuments200Response
     */
    constructor() { 
        
        SearchDocuments200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SearchDocuments200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchDocuments200Response} obj Optional instance to populate.
     * @return {module:model/SearchDocuments200Response} The populated <code>SearchDocuments200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchDocuments200Response();

            if (data.hasOwnProperty('q')) {
                obj['q'] = ApiClient.convertToType(data['q'], 'String');
            }
            if (data.hasOwnProperty('query_id')) {
                obj['query_id'] = ApiClient.convertToType(data['query_id'], 'String');
            }
            if (data.hasOwnProperty('exec_time')) {
                obj['exec_time'] = ApiClient.convertToType(data['exec_time'], 'Number');
            }
            if (data.hasOwnProperty('query_time')) {
                obj['query_time'] = ApiClient.convertToType(data['query_time'], 'Number');
            }
            if (data.hasOwnProperty('page_size')) {
                obj['page_size'] = ApiClient.convertToType(data['page_size'], 'Number');
            }
            if (data.hasOwnProperty('page_number')) {
                obj['page_number'] = ApiClient.convertToType(data['page_number'], 'Number');
            }
            if (data.hasOwnProperty('record_count')) {
                obj['record_count'] = ApiClient.convertToType(data['record_count'], 'Number');
            }
            if (data.hasOwnProperty('page_count')) {
                obj['page_count'] = ApiClient.convertToType(data['page_count'], 'Number');
            }
            if (data.hasOwnProperty('highlight_params')) {
                obj['highlight_params'] = ApiClient.convertToType(data['highlight_params'], 'String');
            }
            if (data.hasOwnProperty('next_page')) {
                obj['next_page'] = ApiClient.convertToType(data['next_page'], 'Boolean');
            }
            if (data.hasOwnProperty('prev_page')) {
                obj['prev_page'] = ApiClient.convertToType(data['prev_page'], 'Boolean');
            }
            if (data.hasOwnProperty('start_record_number')) {
                obj['start_record_number'] = ApiClient.convertToType(data['start_record_number'], 'Number');
            }
            if (data.hasOwnProperty('end_record_number')) {
                obj['end_record_number'] = ApiClient.convertToType(data['end_record_number'], 'Number');
            }
            if (data.hasOwnProperty('page_numbers')) {
                obj['page_numbers'] = ApiClient.convertToType(data['page_numbers'], ['String']);
            }
            if (data.hasOwnProperty('partial')) {
                obj['partial'] = ApiClient.convertToType(data['partial'], 'Boolean');
            }
            if (data.hasOwnProperty('search_query')) {
                obj['search_query'] = ApiClient.convertToType(data['search_query'], 'String');
            }
            if (data.hasOwnProperty('requested_time')) {
                obj['requested_time'] = ApiClient.convertToType(data['requested_time'], 'Number');
            }
            if (data.hasOwnProperty('related_query')) {
                obj['related_query'] = ApiClient.convertToType(data['related_query'], ['String']);
            }
            if (data.hasOwnProperty('related_contents')) {
                obj['related_contents'] = ApiClient.convertToType(data['related_contents'], ['String']);
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [SearchDocuments200ResponseDataInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SearchDocuments200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SearchDocuments200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['q'] && !(typeof data['q'] === 'string' || data['q'] instanceof String)) {
            throw new Error("Expected the field `q` to be a primitive type in the JSON string but got " + data['q']);
        }
        // ensure the json data is a string
        if (data['query_id'] && !(typeof data['query_id'] === 'string' || data['query_id'] instanceof String)) {
            throw new Error("Expected the field `query_id` to be a primitive type in the JSON string but got " + data['query_id']);
        }
        // ensure the json data is a string
        if (data['highlight_params'] && !(typeof data['highlight_params'] === 'string' || data['highlight_params'] instanceof String)) {
            throw new Error("Expected the field `highlight_params` to be a primitive type in the JSON string but got " + data['highlight_params']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['page_numbers'])) {
            throw new Error("Expected the field `page_numbers` to be an array in the JSON data but got " + data['page_numbers']);
        }
        // ensure the json data is a string
        if (data['search_query'] && !(typeof data['search_query'] === 'string' || data['search_query'] instanceof String)) {
            throw new Error("Expected the field `search_query` to be a primitive type in the JSON string but got " + data['search_query']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['related_query'])) {
            throw new Error("Expected the field `related_query` to be an array in the JSON data but got " + data['related_query']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['related_contents'])) {
            throw new Error("Expected the field `related_contents` to be an array in the JSON data but got " + data['related_contents']);
        }
        if (data['data']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['data'])) {
                throw new Error("Expected the field `data` to be an array in the JSON data but got " + data['data']);
            }
            // validate the optional field `data` (array)
            for (const item of data['data']) {
                SearchDocuments200ResponseDataInner.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} q
 */
SearchDocuments200Response.prototype['q'] = undefined;

/**
 * @member {String} query_id
 */
SearchDocuments200Response.prototype['query_id'] = undefined;

/**
 * @member {Number} exec_time
 */
SearchDocuments200Response.prototype['exec_time'] = undefined;

/**
 * @member {Number} query_time
 */
SearchDocuments200Response.prototype['query_time'] = undefined;

/**
 * @member {Number} page_size
 */
SearchDocuments200Response.prototype['page_size'] = undefined;

/**
 * @member {Number} page_number
 */
SearchDocuments200Response.prototype['page_number'] = undefined;

/**
 * @member {Number} record_count
 */
SearchDocuments200Response.prototype['record_count'] = undefined;

/**
 * @member {Number} page_count
 */
SearchDocuments200Response.prototype['page_count'] = undefined;

/**
 * @member {String} highlight_params
 */
SearchDocuments200Response.prototype['highlight_params'] = undefined;

/**
 * @member {Boolean} next_page
 */
SearchDocuments200Response.prototype['next_page'] = undefined;

/**
 * @member {Boolean} prev_page
 */
SearchDocuments200Response.prototype['prev_page'] = undefined;

/**
 * @member {Number} start_record_number
 */
SearchDocuments200Response.prototype['start_record_number'] = undefined;

/**
 * @member {Number} end_record_number
 */
SearchDocuments200Response.prototype['end_record_number'] = undefined;

/**
 * @member {Array.<String>} page_numbers
 */
SearchDocuments200Response.prototype['page_numbers'] = undefined;

/**
 * @member {Boolean} partial
 */
SearchDocuments200Response.prototype['partial'] = undefined;

/**
 * @member {String} search_query
 */
SearchDocuments200Response.prototype['search_query'] = undefined;

/**
 * @member {Number} requested_time
 */
SearchDocuments200Response.prototype['requested_time'] = undefined;

/**
 * @member {Array.<String>} related_query
 */
SearchDocuments200Response.prototype['related_query'] = undefined;

/**
 * @member {Array.<String>} related_contents
 */
SearchDocuments200Response.prototype['related_contents'] = undefined;

/**
 * @member {Array.<module:model/SearchDocuments200ResponseDataInner>} data
 */
SearchDocuments200Response.prototype['data'] = undefined;






export default SearchDocuments200Response;

