/**
 * Fess - User API
 * This is a Fess Server based on the OpenAPI 3.0 specification.  
 *
 * The version of the OpenAPI document: 14.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SearchDocuments200ResponseDataInner model module.
 * @module model/SearchDocuments200ResponseDataInner
 * @version 14.8.0
 */
class SearchDocuments200ResponseDataInner {
    /**
     * Constructs a new <code>SearchDocuments200ResponseDataInner</code>.
     * @alias module:model/SearchDocuments200ResponseDataInner
     */
    constructor() { 
        
        SearchDocuments200ResponseDataInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SearchDocuments200ResponseDataInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchDocuments200ResponseDataInner} obj Optional instance to populate.
     * @return {module:model/SearchDocuments200ResponseDataInner} The populated <code>SearchDocuments200ResponseDataInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchDocuments200ResponseDataInner();

            if (data.hasOwnProperty('filetype')) {
                obj['filetype'] = ApiClient.convertToType(data['filetype'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('content_title')) {
                obj['content_title'] = ApiClient.convertToType(data['content_title'], 'String');
            }
            if (data.hasOwnProperty('digest')) {
                obj['digest'] = ApiClient.convertToType(data['digest'], 'String');
            }
            if (data.hasOwnProperty('host')) {
                obj['host'] = ApiClient.convertToType(data['host'], 'String');
            }
            if (data.hasOwnProperty('last_modified')) {
                obj['last_modified'] = ApiClient.convertToType(data['last_modified'], 'Date');
            }
            if (data.hasOwnProperty('content_length')) {
                obj['content_length'] = ApiClient.convertToType(data['content_length'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
            if (data.hasOwnProperty('url_link')) {
                obj['url_link'] = ApiClient.convertToType(data['url_link'], 'String');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
            if (data.hasOwnProperty('site_path')) {
                obj['site_path'] = ApiClient.convertToType(data['site_path'], 'String');
            }
            if (data.hasOwnProperty('doc_id')) {
                obj['doc_id'] = ApiClient.convertToType(data['doc_id'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('content_description')) {
                obj['content_description'] = ApiClient.convertToType(data['content_description'], 'String');
            }
            if (data.hasOwnProperty('site')) {
                obj['site'] = ApiClient.convertToType(data['site'], 'String');
            }
            if (data.hasOwnProperty('boost')) {
                obj['boost'] = ApiClient.convertToType(data['boost'], 'String');
            }
            if (data.hasOwnProperty('mimetype')) {
                obj['mimetype'] = ApiClient.convertToType(data['mimetype'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SearchDocuments200ResponseDataInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SearchDocuments200ResponseDataInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['filetype'] && !(typeof data['filetype'] === 'string' || data['filetype'] instanceof String)) {
            throw new Error("Expected the field `filetype` to be a primitive type in the JSON string but got " + data['filetype']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['content_title'] && !(typeof data['content_title'] === 'string' || data['content_title'] instanceof String)) {
            throw new Error("Expected the field `content_title` to be a primitive type in the JSON string but got " + data['content_title']);
        }
        // ensure the json data is a string
        if (data['digest'] && !(typeof data['digest'] === 'string' || data['digest'] instanceof String)) {
            throw new Error("Expected the field `digest` to be a primitive type in the JSON string but got " + data['digest']);
        }
        // ensure the json data is a string
        if (data['host'] && !(typeof data['host'] === 'string' || data['host'] instanceof String)) {
            throw new Error("Expected the field `host` to be a primitive type in the JSON string but got " + data['host']);
        }
        // ensure the json data is a string
        if (data['content_length'] && !(typeof data['content_length'] === 'string' || data['content_length'] instanceof String)) {
            throw new Error("Expected the field `content_length` to be a primitive type in the JSON string but got " + data['content_length']);
        }
        // ensure the json data is a string
        if (data['url_link'] && !(typeof data['url_link'] === 'string' || data['url_link'] instanceof String)) {
            throw new Error("Expected the field `url_link` to be a primitive type in the JSON string but got " + data['url_link']);
        }
        // ensure the json data is a string
        if (data['site_path'] && !(typeof data['site_path'] === 'string' || data['site_path'] instanceof String)) {
            throw new Error("Expected the field `site_path` to be a primitive type in the JSON string but got " + data['site_path']);
        }
        // ensure the json data is a string
        if (data['doc_id'] && !(typeof data['doc_id'] === 'string' || data['doc_id'] instanceof String)) {
            throw new Error("Expected the field `doc_id` to be a primitive type in the JSON string but got " + data['doc_id']);
        }
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['content_description'] && !(typeof data['content_description'] === 'string' || data['content_description'] instanceof String)) {
            throw new Error("Expected the field `content_description` to be a primitive type in the JSON string but got " + data['content_description']);
        }
        // ensure the json data is a string
        if (data['site'] && !(typeof data['site'] === 'string' || data['site'] instanceof String)) {
            throw new Error("Expected the field `site` to be a primitive type in the JSON string but got " + data['site']);
        }
        // ensure the json data is a string
        if (data['boost'] && !(typeof data['boost'] === 'string' || data['boost'] instanceof String)) {
            throw new Error("Expected the field `boost` to be a primitive type in the JSON string but got " + data['boost']);
        }
        // ensure the json data is a string
        if (data['mimetype'] && !(typeof data['mimetype'] === 'string' || data['mimetype'] instanceof String)) {
            throw new Error("Expected the field `mimetype` to be a primitive type in the JSON string but got " + data['mimetype']);
        }

        return true;
    }


}



/**
 * @member {String} filetype
 */
SearchDocuments200ResponseDataInner.prototype['filetype'] = undefined;

/**
 * @member {String} title
 */
SearchDocuments200ResponseDataInner.prototype['title'] = undefined;

/**
 * @member {String} content_title
 */
SearchDocuments200ResponseDataInner.prototype['content_title'] = undefined;

/**
 * @member {String} digest
 */
SearchDocuments200ResponseDataInner.prototype['digest'] = undefined;

/**
 * @member {String} host
 */
SearchDocuments200ResponseDataInner.prototype['host'] = undefined;

/**
 * @member {Date} last_modified
 */
SearchDocuments200ResponseDataInner.prototype['last_modified'] = undefined;

/**
 * @member {String} content_length
 */
SearchDocuments200ResponseDataInner.prototype['content_length'] = undefined;

/**
 * @member {Date} timestamp
 */
SearchDocuments200ResponseDataInner.prototype['timestamp'] = undefined;

/**
 * @member {String} url_link
 */
SearchDocuments200ResponseDataInner.prototype['url_link'] = undefined;

/**
 * @member {Date} created
 */
SearchDocuments200ResponseDataInner.prototype['created'] = undefined;

/**
 * @member {String} site_path
 */
SearchDocuments200ResponseDataInner.prototype['site_path'] = undefined;

/**
 * @member {String} doc_id
 */
SearchDocuments200ResponseDataInner.prototype['doc_id'] = undefined;

/**
 * @member {String} url
 */
SearchDocuments200ResponseDataInner.prototype['url'] = undefined;

/**
 * @member {String} content_description
 */
SearchDocuments200ResponseDataInner.prototype['content_description'] = undefined;

/**
 * @member {String} site
 */
SearchDocuments200ResponseDataInner.prototype['site'] = undefined;

/**
 * @member {String} boost
 */
SearchDocuments200ResponseDataInner.prototype['boost'] = undefined;

/**
 * @member {String} mimetype
 */
SearchDocuments200ResponseDataInner.prototype['mimetype'] = undefined;






export default SearchDocuments200ResponseDataInner;

