/* tslint:disable */
/* eslint-disable */
/**
 * Fess - User API
 * This is a Fess Server based on the OpenAPI 3.0 specification.  
 *
 * The version of the OpenAPI document: 14.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SearchDocuments200ResponseDataInner {
    'filetype'?: string;
    'title'?: string;
    'content_title'?: string;
    'digest'?: string;
    'host'?: string;
    'last_modified'?: string;
    'content_length'?: string;
    'timestamp'?: string;
    'url_link'?: string;
    'created'?: string;
    'site_path'?: string;
    'doc_id'?: string;
    'url'?: string;
    'content_description'?: string;
    'site'?: string;
    'boost'?: string;
    'mimetype'?: string;
}

