/* tslint:disable */
/* eslint-disable */
/**
 * Fess - User API
 * This is a Fess Server based on the OpenAPI 3.0 specification.  
 *
 * The version of the OpenAPI document: 14.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ListFavorites200Response } from '../model';
// @ts-ignore
import type { SetFavorite201Response } from '../model';
/**
 * FavoriteApi - axios parameter creator
 */
export const FavoriteApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns favorited document IDs
         * @summary List favorites
         * @param {string} queryId Query ID where the document is contained
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listFavorites: async (queryId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'queryId' is not null or undefined
            assertParamExists('listFavorites', 'queryId', queryId)
            const localVarPath = `/favorites`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (queryId !== undefined) {
                localVarQueryParameter['queryId'] = queryId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Set a favorite mark to the document
         * @summary Set a favorite mark
         * @param {string} docId Document ID to be favorited
         * @param {string} queryId Query ID where the document is contained
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setFavorite: async (docId: string, queryId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'docId' is not null or undefined
            assertParamExists('setFavorite', 'docId', docId)
            // verify required parameter 'queryId' is not null or undefined
            assertParamExists('setFavorite', 'queryId', queryId)
            const localVarPath = `/documents/{docId}/favorite`
                .replace(`{${"docId"}}`, encodeURIComponent(String(docId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (queryId !== undefined) {
                localVarQueryParameter['queryId'] = queryId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FavoriteApi - functional programming interface
 */
export const FavoriteApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FavoriteApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns favorited document IDs
         * @summary List favorites
         * @param {string} queryId Query ID where the document is contained
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listFavorites(queryId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListFavorites200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listFavorites(queryId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FavoriteApi.listFavorites']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Set a favorite mark to the document
         * @summary Set a favorite mark
         * @param {string} docId Document ID to be favorited
         * @param {string} queryId Query ID where the document is contained
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setFavorite(docId: string, queryId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SetFavorite201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setFavorite(docId, queryId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FavoriteApi.setFavorite']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FavoriteApi - factory interface
 */
export const FavoriteApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FavoriteApiFp(configuration)
    return {
        /**
         * Returns favorited document IDs
         * @summary List favorites
         * @param {string} queryId Query ID where the document is contained
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listFavorites(queryId: string, options?: RawAxiosRequestConfig): AxiosPromise<ListFavorites200Response> {
            return localVarFp.listFavorites(queryId, options).then((request) => request(axios, basePath));
        },
        /**
         * Set a favorite mark to the document
         * @summary Set a favorite mark
         * @param {string} docId Document ID to be favorited
         * @param {string} queryId Query ID where the document is contained
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setFavorite(docId: string, queryId: string, options?: RawAxiosRequestConfig): AxiosPromise<SetFavorite201Response> {
            return localVarFp.setFavorite(docId, queryId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FavoriteApi - object-oriented interface
 */
export class FavoriteApi extends BaseAPI {
    /**
     * Returns favorited document IDs
     * @summary List favorites
     * @param {string} queryId Query ID where the document is contained
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listFavorites(queryId: string, options?: RawAxiosRequestConfig) {
        return FavoriteApiFp(this.configuration).listFavorites(queryId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Set a favorite mark to the document
     * @summary Set a favorite mark
     * @param {string} docId Document ID to be favorited
     * @param {string} queryId Query ID where the document is contained
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public setFavorite(docId: string, queryId: string, options?: RawAxiosRequestConfig) {
        return FavoriteApiFp(this.configuration).setFavorite(docId, queryId, options).then((request) => request(this.axios, this.basePath));
    }
}

