/**
 * Fess - User API
 * This is a Fess Server based on the OpenAPI 3.0 specification.  
 *
 * The version of the OpenAPI document: 14.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Error from '../model/Error';
import ListLPopularWords200Response from '../model/ListLPopularWords200Response';

/**
* Popularword service.
* @module api/PopularwordApi
* @version 14.8.0
*/
export default class PopularwordApi {

    /**
    * Constructs a new PopularwordApi. 
    * @alias module:api/PopularwordApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * List popular words
     * Returns available labels
     * @param {Object} opts Optional parameters
     * @param {String} [seed] Random seed to return popular words
     * @param {Array.<String>} [label] Filtered label name
     * @param {Array.<String>} [field] Field name to generate suggest words
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ListLPopularWords200Response} and HTTP response
     */
    listLPopularWordsWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'seed': opts['seed'],
        'label': this.apiClient.buildCollectionParam(opts['label'], 'multi'),
        'field': this.apiClient.buildCollectionParam(opts['field'], 'multi')
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ListLPopularWords200Response;
      return this.apiClient.callApi(
        '/popular-words', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * List popular words
     * Returns available labels
     * @param {Object} opts Optional parameters
     * @param {String} opts.seed Random seed to return popular words
     * @param {Array.<String>} opts.label Filtered label name
     * @param {Array.<String>} opts.field Field name to generate suggest words
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ListLPopularWords200Response}
     */
    listLPopularWords(opts) {
      return this.listLPopularWordsWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
