/* tslint:disable */
/* eslint-disable */
/**
 * Fess - User API
 * This is a Fess Server based on the OpenAPI 3.0 specification.  
 *
 * The version of the OpenAPI document: 14.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ListPopularWords200Response } from '../model';
/**
 * PopularwordApi - axios parameter creator
 */
export const PopularwordApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns available labels
         * @summary List popular words
         * @param {string} [seed] Random seed to return popular words
         * @param {Array<string>} [label] Filtered label name
         * @param {Array<string>} [field] Field name to generate suggest words
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPopularWords: async (seed?: string, label?: Array<string>, field?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/popular-words`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (seed !== undefined) {
                localVarQueryParameter['seed'] = seed;
            }

            if (label) {
                localVarQueryParameter['label'] = label;
            }

            if (field) {
                localVarQueryParameter['field'] = field;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PopularwordApi - functional programming interface
 */
export const PopularwordApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PopularwordApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns available labels
         * @summary List popular words
         * @param {string} [seed] Random seed to return popular words
         * @param {Array<string>} [label] Filtered label name
         * @param {Array<string>} [field] Field name to generate suggest words
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listPopularWords(seed?: string, label?: Array<string>, field?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListPopularWords200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listPopularWords(seed, label, field, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PopularwordApi.listPopularWords']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PopularwordApi - factory interface
 */
export const PopularwordApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PopularwordApiFp(configuration)
    return {
        /**
         * Returns available labels
         * @summary List popular words
         * @param {string} [seed] Random seed to return popular words
         * @param {Array<string>} [label] Filtered label name
         * @param {Array<string>} [field] Field name to generate suggest words
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listPopularWords(seed?: string, label?: Array<string>, field?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<ListPopularWords200Response> {
            return localVarFp.listPopularWords(seed, label, field, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PopularwordApi - object-oriented interface
 */
export class PopularwordApi extends BaseAPI {
    /**
     * Returns available labels
     * @summary List popular words
     * @param {string} [seed] Random seed to return popular words
     * @param {Array<string>} [label] Filtered label name
     * @param {Array<string>} [field] Field name to generate suggest words
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listPopularWords(seed?: string, label?: Array<string>, field?: Array<string>, options?: RawAxiosRequestConfig) {
        return PopularwordApiFp(this.configuration).listPopularWords(seed, label, field, options).then((request) => request(this.axios, this.basePath));
    }
}

