/* tslint:disable */
/* eslint-disable */
/**
 * Fess - User API
 * This is a Fess Server based on the OpenAPI 3.0 specification.  
 *
 * The version of the OpenAPI document: 14.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ListLabels200Response } from '../model';
// @ts-ignore
import type { SearchDocuments200Response } from '../model';
/**
 * SearchApi - axios parameter creator
 */
export const SearchApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns available labels
         * @summary List labels
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listLabels: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/labels`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Finds all documents by search conditions
         * @summary Finds all documents by query
         * @param {string} [q] Search words
         * @param {number} [num] The number of returned documents as a search result
         * @param {string} [sort] Sorted field name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchAllDocuments: async (q?: string, num?: number, sort?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/documents/all`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }

            if (num !== undefined) {
                localVarQueryParameter['num'] = num;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            localVarHeaderParameter['Accept'] = 'application/x-ndjson,application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Finds documents by search conditions
         * @summary Finds documents by query
         * @param {string} [q] Search words
         * @param {number} [start] Start position
         * @param {number} [offset] Offset from a start position
         * @param {number} [num] The number of returned documents as a search result
         * @param {string} [sort] Sorted field name
         * @param {Array<string>} [fieldsLabel] Filtered label name
         * @param {Array<string>} [facetField] Facet field name
         * @param {Array<string>} [facetQuery] Facet query
         * @param {number} [facetSize] Item size in facets returned by facet.field
         * @param {number} [facetMinDocCount] Minumum document size in facets
         * @param {string} [geoLocationPoint] Latitude and Longitude for Geo search
         * @param {string} [geoLocationDistance] Distance for Geo search
         * @param {string} [lang] Language
         * @param {string} [preference] String to specify a shard for searching
         * @param {string} [callback] Callback name for using JSONP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchDocuments: async (q?: string, start?: number, offset?: number, num?: number, sort?: string, fieldsLabel?: Array<string>, facetField?: Array<string>, facetQuery?: Array<string>, facetSize?: number, facetMinDocCount?: number, geoLocationPoint?: string, geoLocationDistance?: string, lang?: string, preference?: string, callback?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/documents`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }

            if (start !== undefined) {
                localVarQueryParameter['start'] = start;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (num !== undefined) {
                localVarQueryParameter['num'] = num;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (fieldsLabel) {
                localVarQueryParameter['fields.label'] = fieldsLabel;
            }

            if (facetField) {
                localVarQueryParameter['facet.field'] = facetField;
            }

            if (facetQuery) {
                localVarQueryParameter['facet.query'] = facetQuery;
            }

            if (facetSize !== undefined) {
                localVarQueryParameter['facet.size'] = facetSize;
            }

            if (facetMinDocCount !== undefined) {
                localVarQueryParameter['facet.minDocCount'] = facetMinDocCount;
            }

            if (geoLocationPoint !== undefined) {
                localVarQueryParameter['geo.location.point'] = geoLocationPoint;
            }

            if (geoLocationDistance !== undefined) {
                localVarQueryParameter['geo.location.distance'] = geoLocationDistance;
            }

            if (lang !== undefined) {
                localVarQueryParameter['lang'] = lang;
            }

            if (preference !== undefined) {
                localVarQueryParameter['preference'] = preference;
            }

            if (callback !== undefined) {
                localVarQueryParameter['callback'] = callback;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SearchApi - functional programming interface
 */
export const SearchApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SearchApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns available labels
         * @summary List labels
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listLabels(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListLabels200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listLabels(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SearchApi.listLabels']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Finds all documents by search conditions
         * @summary Finds all documents by query
         * @param {string} [q] Search words
         * @param {number} [num] The number of returned documents as a search result
         * @param {string} [sort] Sorted field name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchAllDocuments(q?: string, num?: number, sort?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchAllDocuments(q, num, sort, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SearchApi.searchAllDocuments']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Finds documents by search conditions
         * @summary Finds documents by query
         * @param {string} [q] Search words
         * @param {number} [start] Start position
         * @param {number} [offset] Offset from a start position
         * @param {number} [num] The number of returned documents as a search result
         * @param {string} [sort] Sorted field name
         * @param {Array<string>} [fieldsLabel] Filtered label name
         * @param {Array<string>} [facetField] Facet field name
         * @param {Array<string>} [facetQuery] Facet query
         * @param {number} [facetSize] Item size in facets returned by facet.field
         * @param {number} [facetMinDocCount] Minumum document size in facets
         * @param {string} [geoLocationPoint] Latitude and Longitude for Geo search
         * @param {string} [geoLocationDistance] Distance for Geo search
         * @param {string} [lang] Language
         * @param {string} [preference] String to specify a shard for searching
         * @param {string} [callback] Callback name for using JSONP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchDocuments(q?: string, start?: number, offset?: number, num?: number, sort?: string, fieldsLabel?: Array<string>, facetField?: Array<string>, facetQuery?: Array<string>, facetSize?: number, facetMinDocCount?: number, geoLocationPoint?: string, geoLocationDistance?: string, lang?: string, preference?: string, callback?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SearchDocuments200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchDocuments(q, start, offset, num, sort, fieldsLabel, facetField, facetQuery, facetSize, facetMinDocCount, geoLocationPoint, geoLocationDistance, lang, preference, callback, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SearchApi.searchDocuments']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SearchApi - factory interface
 */
export const SearchApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SearchApiFp(configuration)
    return {
        /**
         * Returns available labels
         * @summary List labels
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listLabels(options?: RawAxiosRequestConfig): AxiosPromise<ListLabels200Response> {
            return localVarFp.listLabels(options).then((request) => request(axios, basePath));
        },
        /**
         * Finds all documents by search conditions
         * @summary Finds all documents by query
         * @param {string} [q] Search words
         * @param {number} [num] The number of returned documents as a search result
         * @param {string} [sort] Sorted field name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchAllDocuments(q?: string, num?: number, sort?: string, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.searchAllDocuments(q, num, sort, options).then((request) => request(axios, basePath));
        },
        /**
         * Finds documents by search conditions
         * @summary Finds documents by query
         * @param {string} [q] Search words
         * @param {number} [start] Start position
         * @param {number} [offset] Offset from a start position
         * @param {number} [num] The number of returned documents as a search result
         * @param {string} [sort] Sorted field name
         * @param {Array<string>} [fieldsLabel] Filtered label name
         * @param {Array<string>} [facetField] Facet field name
         * @param {Array<string>} [facetQuery] Facet query
         * @param {number} [facetSize] Item size in facets returned by facet.field
         * @param {number} [facetMinDocCount] Minumum document size in facets
         * @param {string} [geoLocationPoint] Latitude and Longitude for Geo search
         * @param {string} [geoLocationDistance] Distance for Geo search
         * @param {string} [lang] Language
         * @param {string} [preference] String to specify a shard for searching
         * @param {string} [callback] Callback name for using JSONP
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchDocuments(q?: string, start?: number, offset?: number, num?: number, sort?: string, fieldsLabel?: Array<string>, facetField?: Array<string>, facetQuery?: Array<string>, facetSize?: number, facetMinDocCount?: number, geoLocationPoint?: string, geoLocationDistance?: string, lang?: string, preference?: string, callback?: string, options?: RawAxiosRequestConfig): AxiosPromise<SearchDocuments200Response> {
            return localVarFp.searchDocuments(q, start, offset, num, sort, fieldsLabel, facetField, facetQuery, facetSize, facetMinDocCount, geoLocationPoint, geoLocationDistance, lang, preference, callback, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SearchApi - object-oriented interface
 */
export class SearchApi extends BaseAPI {
    /**
     * Returns available labels
     * @summary List labels
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listLabels(options?: RawAxiosRequestConfig) {
        return SearchApiFp(this.configuration).listLabels(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Finds all documents by search conditions
     * @summary Finds all documents by query
     * @param {string} [q] Search words
     * @param {number} [num] The number of returned documents as a search result
     * @param {string} [sort] Sorted field name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public searchAllDocuments(q?: string, num?: number, sort?: string, options?: RawAxiosRequestConfig) {
        return SearchApiFp(this.configuration).searchAllDocuments(q, num, sort, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Finds documents by search conditions
     * @summary Finds documents by query
     * @param {string} [q] Search words
     * @param {number} [start] Start position
     * @param {number} [offset] Offset from a start position
     * @param {number} [num] The number of returned documents as a search result
     * @param {string} [sort] Sorted field name
     * @param {Array<string>} [fieldsLabel] Filtered label name
     * @param {Array<string>} [facetField] Facet field name
     * @param {Array<string>} [facetQuery] Facet query
     * @param {number} [facetSize] Item size in facets returned by facet.field
     * @param {number} [facetMinDocCount] Minumum document size in facets
     * @param {string} [geoLocationPoint] Latitude and Longitude for Geo search
     * @param {string} [geoLocationDistance] Distance for Geo search
     * @param {string} [lang] Language
     * @param {string} [preference] String to specify a shard for searching
     * @param {string} [callback] Callback name for using JSONP
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public searchDocuments(q?: string, start?: number, offset?: number, num?: number, sort?: string, fieldsLabel?: Array<string>, facetField?: Array<string>, facetQuery?: Array<string>, facetSize?: number, facetMinDocCount?: number, geoLocationPoint?: string, geoLocationDistance?: string, lang?: string, preference?: string, callback?: string, options?: RawAxiosRequestConfig) {
        return SearchApiFp(this.configuration).searchDocuments(q, start, offset, num, sort, fieldsLabel, facetField, facetQuery, facetSize, facetMinDocCount, geoLocationPoint, geoLocationDistance, lang, preference, callback, options).then((request) => request(this.axios, this.basePath));
    }
}

