/* tslint:disable */
/* eslint-disable */
/**
 * Fess - User API
 * This is a Fess Server based on the OpenAPI 3.0 specification.  
 *
 * The version of the OpenAPI document: 14.8.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { FindSuggestWords200Response } from '../model';
/**
 * SuggestApi - axios parameter creator
 */
export const SuggestApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns words for suggest
         * @summary Finds suggest words
         * @param {string} q Inputting characters for search
         * @param {number} [num] The number of suggest words
         * @param {Array<string>} [label] Filtered label name
         * @param {Array<string>} [field] Field name to generate suggest words
         * @param {Array<string>} [lang] Target language
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findSuggestWords: async (q: string, num?: number, label?: Array<string>, field?: Array<string>, lang?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'q' is not null or undefined
            assertParamExists('findSuggestWords', 'q', q)
            const localVarPath = `/suggest-words`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }

            if (num !== undefined) {
                localVarQueryParameter['num'] = num;
            }

            if (label) {
                localVarQueryParameter['label'] = label;
            }

            if (field) {
                localVarQueryParameter['field'] = field;
            }

            if (lang) {
                localVarQueryParameter['lang'] = lang;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SuggestApi - functional programming interface
 */
export const SuggestApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SuggestApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns words for suggest
         * @summary Finds suggest words
         * @param {string} q Inputting characters for search
         * @param {number} [num] The number of suggest words
         * @param {Array<string>} [label] Filtered label name
         * @param {Array<string>} [field] Field name to generate suggest words
         * @param {Array<string>} [lang] Target language
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async findSuggestWords(q: string, num?: number, label?: Array<string>, field?: Array<string>, lang?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FindSuggestWords200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.findSuggestWords(q, num, label, field, lang, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SuggestApi.findSuggestWords']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SuggestApi - factory interface
 */
export const SuggestApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SuggestApiFp(configuration)
    return {
        /**
         * Returns words for suggest
         * @summary Finds suggest words
         * @param {string} q Inputting characters for search
         * @param {number} [num] The number of suggest words
         * @param {Array<string>} [label] Filtered label name
         * @param {Array<string>} [field] Field name to generate suggest words
         * @param {Array<string>} [lang] Target language
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        findSuggestWords(q: string, num?: number, label?: Array<string>, field?: Array<string>, lang?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<FindSuggestWords200Response> {
            return localVarFp.findSuggestWords(q, num, label, field, lang, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SuggestApi - object-oriented interface
 */
export class SuggestApi extends BaseAPI {
    /**
     * Returns words for suggest
     * @summary Finds suggest words
     * @param {string} q Inputting characters for search
     * @param {number} [num] The number of suggest words
     * @param {Array<string>} [label] Filtered label name
     * @param {Array<string>} [field] Field name to generate suggest words
     * @param {Array<string>} [lang] Target language
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public findSuggestWords(q: string, num?: number, label?: Array<string>, field?: Array<string>, lang?: Array<string>, options?: RawAxiosRequestConfig) {
        return SuggestApiFp(this.configuration).findSuggestWords(q, num, label, field, lang, options).then((request) => request(this.axios, this.basePath));
    }
}

